name: Build and Publish

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"

env:
  DOCKER_IMAGE: minecraft-server
  REGION: us-central1
  GCLOUD_PROJECT_ID: docker-minecraft-server
  GCLOUD_PROJECT_NAME: docker-minecraft-server

jobs:
  build-and-push:
    runs-on: ubuntu-20.04 #

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Prepare
      id: prep
      run: |
        VERSION=edge
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        if [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=${GITHUB_REF#refs/heads/}
          if [[ $VERSION == master ]]; then
            VERSION=latest
          fi
        fi
        TAGS="${{env.DOCKER_IMAGE}}:${VERSION//\//-}"
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=version::${VERSION//\//-}
    
    ## BUILD AND PUSH TO GCP
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: `google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2.8.0
      with:
        context: .
        file: ./Dockerfile
        pull: true
        load: true
        push: false
        tags: gcr.io/${{ env.GCLOUD_PROJECT_ID }}/${{ env.GCLOUD_PROJECT_NAME }}:${{  github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          org.opencontainers.image.documentation=https://github.com/itzg/docker-minecraft-server
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.source=https://github.com/itzg/docker-minecraft-server
          org.opencontainers.image.revision=${{ github.sha }}

    - name: what images are there then
      run: docker image ls

    - name: Push Container
      run: |-
        docker push gcr.io/${{ env.GCLOUD_PROJECT_ID }}/${{ env.GCLOUD_PROJECT_NAME }}:${{  github.sha }}
      
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}