name: Build and Publish

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"

env:
  DOCKER_IMAGE: minecraft-server
  REGION: us-central1

jobs:
  build-and-push:
    runs-on: ubuntu-20.04 #

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Prepare
      id: prep
      run: |
        VERSION=edge
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        if [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=${GITHUB_REF#refs/heads/}
          if [[ $VERSION == master ]]; then
            VERSION=latest
          fi
        fi
        TAGS="${{env.DOCKER_IMAGE}}:${VERSION//\//-}"
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=version::${VERSION//\//-}
    
    ## BUILD AND PUSH TO AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_MINECRAFT_ECS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_MINECRAFT_ECS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2.8.0
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: minecraft-server-docker
        IMAGE_TAG: ${{ github.sha }}-prod
      with:
        context: .
        file: ./Dockerfile
        pull: true
        load: true
        push: false
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: |
          org.opencontainers.image.documentation=https://github.com/itzg/docker-minecraft-server
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.source=https://github.com/itzg/docker-minecraft-server
          org.opencontainers.image.revision=${{ github.sha }}

    - name: List Images
      run: docker image ls

    - name: Push Container
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: minecraft-server-docker
        IMAGE_TAG: ${{ github.sha }}-prod
      run: |-
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG}}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}