name: Build and Publish

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"

env:
  DOCKER_IMAGE: minecraft-server
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  REGION: us-central1

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0

    - name: print some stuff
      run: echo ${{secrets.GCLOUD_PROJECT_ID}}

    - name: Prepare
      id: prep
      run: |
        VERSION=edge
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        if [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=${GITHUB_REF#refs/heads/}
          if [[ $VERSION == master ]]; then
            VERSION=latest
          fi
        fi
        TAGS="${{env.DOCKER_IMAGE}}:${VERSION//\//-}"
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=version::${VERSION//\//-}

    
    ## BUILD AND PUSH TO GCP
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id:  ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Authorize Docker and Build and Push Container
      run: |-
        gcloud auth configure-docker
        docker build -t gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_PROJECT_NAME }}:${{  github.sha }} .
        docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_PROJECT_NAME }}:${{  github.sha }}
      
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}